name: GitHub Actions Build and Deploy Demo
on:
  push:
    branches:
      - dev
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1    
    - name: Checkout
      run: |
        echo 123
        mkdir public
        ls

    - name: Build and Deploy
      uses: JamesIves/github-pages-deploy-action@master 
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: dev
        FOLDER: public
        BUILD_SCRIPT: npm install hexo-cli -g &&  npm install && hexo g && ls
