#https://github.com/marketplace/actions/deploy-to-github-pages
name: GitHub Actions Build and Deploy Demo
on:
  push:
    branches:
      - dev
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master    
    - name: Checkout
      run: |
        echo 123
        mkdir public
        ls

    - name: Build and Deploy
      uses: JamesIves/github-pages-deploy-action@master 
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        BASE_BRANCH: dev
        BRANCH: master # gh-pages
        FOLDER: public  #build|dist|public ...
        #TARGET_FOLDER: public
        CLEAN: 'true'
        CLEAN_EXCLUDE: '[]'
        BUILD_SCRIPT: npm install hexo-cli -g &&  npm install && hexo g && ls
